<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/announcements.php';
require_once __DIR__ . '/includes/live_search.php';
require_auth();
require_once __DIR__ . '/includes/navigation.php';
if (!can_access_navigation('announcements')) { http_response_code(403); exit('Access denied.'); }
$connection = db();
$tab = (string) ($_GET['tab'] ?? 'published');
$search = trim((string) ($_GET['q'] ?? ''));
$tabs = announcements_can_manage() ? ['published', 'drafts', 'archived'] : ['published'];
if (!in_array($tab, $tabs, true)) $tab = 'published';
$status = $tab === 'drafts' ? 'draft' : ($tab === 'archived' ? 'archived' : 'published');
$params = [':status' => $status];
$visibility = announcements_visibility_sql($connection, $params);
$sql = "SELECT a.id, a.title, a.body, a.audience, a.target_purok, a.status, a.published_at, a.created_at FROM announcements a WHERE a.status = :status AND $visibility";
if ($search !== '') { $sql .= ' AND a.title LIKE :search'; $params[':search'] = '%' . $search . '%'; }
$sql .= $status === 'published' ? ' ORDER BY a.published_at DESC, a.id DESC' : ' ORDER BY a.created_at DESC, a.id DESC';
$statement = $connection->prepare($sql);
$statement->execute($params);
$records = $statement->fetchAll();
// Results markup shared by the full page and Live Search responses; the tab, visibility rules and actions are the same in both.
$render_results = static function () use ($records, $search, $tab): void {
    if ($records === []): ?><div class="dashboard-empty-state"><?php if ($search !== ''): ?>No matching records found.<?php else: ?>No <?= e($tab) ?> announcements available.<?php if (announcements_can_manage()): ?><a class="announcement-action" href="announcement_form.php">Add Announcement</a><?php endif; ?><?php endif; ?></div><?php else: ?><div class="management-list"><?php foreach ($records as $record): ?><article class="management-row"><div><a class="management-title" href="announcement_view.php?id=<?= e((string) $record['id']) ?>"><h2><?= e($record['title']) ?></h2></a><p><?= e(announcements_preview($record['body'])) ?></p><small><?= e(announcements_audience_label($record['audience'])) ?> · <?= e(announcements_format_date($record['status'] === 'published' ? $record['published_at'] : $record['created_at'])) ?></small></div><div class="management-actions"><div class="action-menu-wrap"><button class="action-menu-btn" type="button" aria-label="Actions" aria-expanded="false" aria-haspopup="true" data-action-menu>&#8942;</button><div class="action-menu-dropdown" hidden><a class="action-menu-item" href="announcement_view.php?id=<?= e((string) $record['id']) ?>">View</a><?php if (announcements_can_manage()): ?><?php if ($record['status'] !== 'archived'): ?><a class="action-menu-item" href="announcement_form.php?id=<?= e((string) $record['id']) ?>">Edit</a><?php endif; ?><?php if ($record['status'] === 'draft'): ?><button class="action-menu-item" type="button" data-confirm-action="publish" data-confirm-id="<?= e((string) $record['id']) ?>" data-confirm-title="<?= e($record['title']) ?>">Publish</button><?php elseif ($record['status'] === 'published'): ?><button class="action-menu-item" type="button" data-confirm-action="archive" data-confirm-id="<?= e((string) $record['id']) ?>" data-confirm-title="<?= e($record['title']) ?>">Archive</button><?php endif; ?><?php if (in_array($record['status'], ['published', 'archived'], true)): ?><form method="post" action="announcement_resend_sms.php" onsubmit="return confirm('Resend SMS notification for this announcement to all eligible residents?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e((string) $record['id']) ?>"><button class="action-menu-item action-menu-item-sms" type="submit">Resend SMS</button></form><?php endif; ?><?php if ($record['status'] === 'archived'): ?><button class="action-menu-item" type="button" data-confirm-action="unarchive" data-confirm-id="<?= e((string) $record['id']) ?>" data-confirm-title="<?= e($record['title']) ?>">Unarchive</button><button class="action-menu-item action-menu-item-danger" type="button" data-confirm-action="delete" data-confirm-id="<?= e((string) $record['id']) ?>" data-confirm-title="<?= e($record['title']) ?>">Delete</button><?php endif; ?><?php endif; ?></div></div></div></article><?php endforeach; ?></div><?php endif;
};
if (live_search_is_request()) live_search_respond($render_results);
$page_title = 'Announcements'; $active_page = 'announcements';
require __DIR__ . '/layout/header.php';
?>
<div class="app-shell"><?php require __DIR__ . '/layout/sidebar.php'; ?><div class="app-main"><?php require __DIR__ . '/layout/topbar.php'; ?><main class="content"><div class="page-heading"><div><h1>Announcements</h1><p>Published community information and announcement records.</p></div><?php if (announcements_can_manage()): ?><a class="btn btn-primary announcements-new-btn" href="announcement_form.php">New Announcement</a><?php endif; ?></div><?php if ($success = flash('announcement_success')): ?><div class="announcement-flash" role="status"><?= e($success) ?></div><?php endif; ?><?php if ($failure = flash('announcement_error')): ?><div class="dashboard-status warning" role="alert"><?= e($failure) ?></div><?php endif; ?><section class="dashboard-panel announcements-page"><div class="announcement-toolbar"><nav class="announcement-tabs page-tabs" aria-label="Announcement status tabs"><?php foreach ($tabs as $available): ?><a class="announcement-tab <?= $tab === $available ? 'active' : '' ?>" href="announcements.php?tab=<?= e($available) ?>"> <?= e(ucfirst($available)) ?></a><?php endforeach; ?></nav><form class="announcement-search" method="get" data-live-search data-live-target="#announcement-results" data-live-status="#announcement-search-status"><input type="hidden" name="tab" value="<?= e($tab) ?>"><input type="search" name="q" value="<?= e($search) ?>" placeholder="Search by title" aria-label="Search announcements by title" autocomplete="off" data-live-query><button class="btn btn-primary" type="submit" data-live-submit>Search</button></form></div><p class="live-search-status" id="announcement-search-status" aria-live="polite"></p><div id="announcement-results" class="live-search-results"><?php $render_results(); ?></div><?php if (announcements_can_manage()): ?><dialog class="announcement-confirm-dialog" id="announcement-confirm-dialog" aria-labelledby="announcement-confirm-heading" aria-describedby="announcement-confirm-name announcement-confirm-detail"><form method="post" action="announcement_action.php"><?= csrf_field() ?><input type="hidden" name="id" value="" data-confirm-id-input><input type="hidden" name="action" value="" data-confirm-action-input><h2 id="announcement-confirm-heading" data-confirm-heading></h2><p class="announcement-confirm-title" id="announcement-confirm-name" data-confirm-name></p><p id="announcement-confirm-detail" data-confirm-detail></p><div class="announcement-confirm-actions"><button class="btn btn-light" type="button" data-confirm-cancel>Cancel</button><button class="btn announcement-confirm-submit" type="submit" data-confirm-submit></button></div></form></dialog><?php endif; ?></section></main><?php require __DIR__ . '/layout/footer.php'; ?></div></div>
