<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/health_programs.php';
require_once __DIR__ . '/includes/report_xlsx.php';
$connection = db();
health_programs_require($connection);

// Excel (.xlsx) of the Monthly Health Report: sheet "Report" (barangay, month, Purok, generated) and "Summary"
// (every section's counts). Counts only; no names.
$state = health_monthly_state($connection, $_GET);
$sections = health_monthly_data($connection, $state);
$scope = residents_purok_scope($connection);
$user = current_user();
$info = [
    ['Barangay', 'BARANGAY SAN JOSE, Quirino, Isabela'], ['Report', 'Monthly Health Report'], ['Month', $state['label']],
    ['Purok', $state['purok'] !== '' ? residents_purok_label($state['purok']) : ($scope !== null ? implode(', ', array_map('residents_purok_label', $scope)) : 'All Puroks')],
    ['Generated', date('F j, Y g:i A')], ['Generated by', $user['name'] . ', ' . role_title()],
    ['Note', 'Summary counts only. Health information is protected under the Data Privacy Act of 2012.'],
];
$summary = [];
foreach ($sections as [$title, $rows, $note]) {
    foreach ($rows as [$label, $value]) $summary[] = [$title, $label, (int) $value];
    $summary[] = [$title, 'Note: ' . $note, ''];
}
$content = report_xlsx_build([
    ['name' => 'Report', 'columns' => [['label' => 'Item', 'width' => 18, 'type' => 'text'], ['label' => 'Value', 'width' => 90, 'type' => 'text']], 'rows' => $info],
    ['name' => 'Summary', 'columns' => [['label' => 'Section', 'width' => 30, 'type' => 'text'], ['label' => 'Item', 'width' => 60, 'type' => 'text'], ['label' => 'Count', 'width' => 12, 'type' => 'number']], 'rows' => $summary],
]);
health_audit($connection, 0, 'health_monthly_exported', ['month' => $state['month'], 'purok' => $state['purok']]);
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="sjqibms-monthly-health-report-' . $state['month'] . '.xlsx"');
header('Content-Length: ' . strlen($content));
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');
echo $content;
