<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/report_modules.php';
require_once __DIR__ . '/includes/report_xlsx.php';

// Excel (.xlsx) version of a module report: the same report structure and filters as the screen. Sheets: "Report"
// (barangay, title, filters, generated at / by, signature lines), "Summary" (cards, chart figures and summary tables)
// and "Details" (the full detail list).
$key = (string) ($_GET['report'] ?? '');
report_require($key);
$connection = db();
try {
    if (!report_module_ready($connection, $key)) { http_response_code(404); exit('This report is not yet available.'); }
    $filters = report_filters($connection, $key, $_GET);
    $report = report_build($connection, $key, $filters, REPORT_EXPORT_LIMIT, 0);
    $filters_text = report_filters_text($connection, $key, $filters);
} catch (Throwable) {
    http_response_code(500);
    exit('This report could not be generated right now. Please try again later.');
}
$user = current_user();
$info = [['Barangay', 'BARANGAY SAN JOSE, Quirino, Isabela'], ['Report', $report['title']]];
foreach ($filters_text as $text) $info[] = ['Filter', $text];
$info[] = ['Generated', date('F j, Y g:i A')];
$info[] = ['Generated by', $user['name'] . ', ' . role_title()];
if ($report['empty']) $info[] = ['Note', 'No data for the selected filters.'];
foreach ($report['notes'] as $note) $info[] = ['Note', $note];
$info[] = ['Prepared by', $user['name'] . ' (' . role_title() . ') — signature: ____________________'];
$info[] = ['Noted by', 'Punong Barangay — signature over printed name: ____________________'];

// Summary: every figure as [section, item, value] (money and counts as numbers where they are plain numbers).
$summary = [];
if (!$report['empty']) {
    foreach ($report['cards'] as [$label, $value, $hint]) $summary[] = ['Summary', $label, $value, $hint];
    foreach ($report['charts'] as $chart) {
        if (!report_chart_has_data($chart)) continue;
        foreach ($chart['labels'] as $i => $label) foreach ($chart['datasets'] as $dataset) $summary[] = [$chart['title'], (string) $label . (count($chart['datasets']) > 1 ? ' — ' . $dataset['label'] : ''), $dataset['data'][$i] ?? 0, !empty($chart['money']) ? 'PHP' : ''];
    }
    foreach ($report['tables'] as $table) foreach ($table['rows'] as $row) $summary[] = [$table['title'], (string) $row[0], implode(' · ', array_slice(array_map('strval', $row), 1)), implode(' · ', array_slice($table['columns'], 1))];
}
$detail_columns = array_map(static fn (string $label): array => ['label' => $label, 'width' => 22, 'type' => 'text'], $report['detail']['columns']);
$content = report_xlsx_build([
    ['name' => 'Report', 'columns' => [['label' => 'Item', 'width' => 18, 'type' => 'text'], ['label' => 'Value', 'width' => 90, 'type' => 'text']], 'rows' => $info],
    ['name' => 'Summary', 'columns' => [['label' => 'Section', 'width' => 36, 'type' => 'text'], ['label' => 'Item', 'width' => 36, 'type' => 'text'], ['label' => 'Value', 'width' => 26, 'type' => 'number'], ['label' => 'Basis / unit', 'width' => 40, 'type' => 'text']], 'rows' => $summary],
    ['name' => 'Details', 'columns' => $detail_columns, 'rows' => $report['detail']['rows']],
]);
report_audit($connection, $key, 'report_exported', $filters);
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="sjqibms-' . $key . '-report-' . $filters['from'] . '-to-' . $filters['to'] . '.xlsx"');
header('Content-Length: ' . strlen($content));
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');
echo $content;
