<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/report_modules.php';

// Printable A4 version of a module report (Print and Export PDF). It renders the same report structure as the screen
// with the same filters — cards, chart figures (as tables), summary tables and the full detail list — plus the barangay
// header, filters used, date and time generated, generated by, and signature lines. "Print / Save as PDF" uses the
// browser's print dialog; ?print=1 opens it automatically.
$key = (string) ($_GET['report'] ?? '');
report_require($key);
$connection = db();
try {
    if (!report_module_ready($connection, $key)) { http_response_code(404); exit('This report is not yet available.'); }
    $filters = report_filters($connection, $key, $_GET);
    $report = report_build($connection, $key, $filters, REPORT_EXPORT_LIMIT, 0);
    $filters_text = report_filters_text($connection, $key, $filters);
} catch (Throwable) {
    http_response_code(500);
    exit('This report could not be generated right now. Please try again later.');
}
report_audit($connection, $key, 'report_printed', $filters);
$user = current_user();
$generated = date('F j, Y g:i A');
$auto_print = ($_GET['print'] ?? '') === '1';
$back = 'module_report.php?' . report_query($key, $filters, ['page' => 1]);
$table = static function (array $columns, array $rows, bool $numeric = true): string {
    $html = '<table class="rpp-table"><thead><tr>';
    foreach ($columns as $i => $column) $html .= '<th' . ($numeric && $i > 0 ? ' class="num"' : '') . '>' . e($column) . '</th>';
    $html .= '</tr></thead><tbody>';
    foreach ($rows as $row) {
        $html .= '<tr' . (($row[0] ?? '') === 'Total' ? ' class="rpp-total"' : '') . '>';
        foreach ($row as $i => $cell) $html .= '<td' . ($numeric && $i > 0 ? ' class="num"' : '') . '>' . e((string) $cell) . '</td>';
        $html .= '</tr>';
    }
    return $html . '</tbody></table>';
};
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <title><?= e($report['title']) ?> | SJQIBMS</title>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="assets/css/report_print.css?v=<?= e((string) @filemtime(__DIR__ . '/assets/css/report_print.css')) ?>" rel="stylesheet">
</head>
<body class="rpp-page">
<div class="rpp-toolbar">
    <span><?= e($report['title']) ?> · <?= e(report_range_label($filters['from'], $filters['to'])) ?></span>
    <div class="rpp-actions"><a href="<?= e($back) ?>">&larr; Back to report</a><button class="is-primary" type="button" data-print>Print / Save as PDF</button></div>
</div>
<main class="rpp-stage">
    <article class="rpp-sheet">
        <header class="rpp-header">
            <img class="rpp-logo" src="assets/img/barangay-san-jose-logo.jpg" alt="Barangay San Jose seal">
            <div class="rpp-header-text"><p>Republic of the Philippines</p><p>Province of Isabela</p><p>Municipality of Quirino</p><p class="rpp-barangay">BARANGAY SAN JOSE</p></div>
        </header>
        <h1 class="rpp-title"><?= e(strtoupper($report['title'])) ?></h1>
        <table class="rpp-info">
            <tr><th>Filters</th><td><?= e(implode(' · ', $filters_text)) ?></td></tr>
            <tr><th>Generated</th><td><?= e($generated) ?></td></tr>
            <tr><th>Generated by</th><td><?= e($user['name'] . ', ' . role_title()) ?></td></tr>
        </table>
        <?php if ($report['empty']): ?>
            <p class="rpp-empty">No data for the selected filters.</p>
        <?php else: ?>
            <h2>Summary</h2>
            <?= $table(['Figure', 'Value', 'Basis'], array_map(static fn (array $c): array => [$c[0], $c[1], $c[2]], $report['cards'])) ?>
            <?php foreach ($report['charts'] as $chart): if (!report_chart_has_data($chart)) continue; $money = !empty($chart['money']); ?>
                <h2><?= e($chart['title']) ?></h2>
                <?= $table(array_merge([$chart['x'] ?? ''], array_column($chart['datasets'], 'label')), array_map(static fn (int $i, $label): array => array_merge([(string) $label], array_map(static fn (array $d): string => $money ? report_peso($d['data'][$i] ?? 0) : report_number($d['data'][$i] ?? 0), $chart['datasets'])), array_keys($chart['labels']), $chart['labels'])) ?>
            <?php endforeach; ?>
            <?php foreach ($report['tables'] as $summary): if ($summary['rows'] === []) continue; ?>
                <h2><?= e($summary['title']) ?></h2>
                <?= $table($summary['columns'], $summary['rows']) ?>
            <?php endforeach; ?>
        <?php endif; ?>
        <h2><?= e($report['detail']['title']) ?> (<?= e(report_number($report['detail']['total'])) ?>)</h2>
        <?php if ($report['detail']['rows'] === []): ?><p class="rpp-empty">No data for the selected filters.</p><?php else: ?>
            <?= $table($report['detail']['columns'], $report['detail']['rows'], false) ?>
            <?php if ($report['detail']['total'] > count($report['detail']['rows'])): ?><p class="rpp-note">Showing the first <?= e(report_number(count($report['detail']['rows']))) ?> of <?= e(report_number($report['detail']['total'])) ?> records. Narrow the filters to include the rest.</p><?php endif; ?>
        <?php endif; ?>
        <?php foreach ($report['notes'] as $note): ?><p class="rpp-note"><?= e($note) ?></p><?php endforeach; ?>
        <section class="rpp-signatures">
            <div class="rpp-sign"><p class="rpp-sign-label">Prepared by:</p><div class="rpp-sign-line"></div><p class="rpp-sign-name"><?= e((string) $user['name']) ?></p><p class="rpp-sign-pos"><?= e(role_title()) ?></p></div>
            <div class="rpp-sign"><p class="rpp-sign-label">Noted by:</p><div class="rpp-sign-line"></div><p class="rpp-sign-name">&nbsp;</p><p class="rpp-sign-pos">Punong Barangay</p></div>
        </section>
        <footer class="rpp-footer">System-generated by SJQIBMS on <?= e($generated) ?>. Figures are computed from the records in the system at the time of generation.</footer>
    </article>
</main>
<script>
document.querySelector('[data-print]').addEventListener('click', () => window.print());
<?php if ($auto_print): ?>window.addEventListener('load', () => window.print());<?php endif; ?>
</script>
</body>
</html>
